### ISSUE TITLE
macOS Ventura 13.0 sync fails due to com.apple.provenance metadata

### ISSUE THREAD

**Issue by luckman212** [xor-gate/syncthing-macosx#185] opened 2022-11-05 21:23 UTC
**update:** This should be fixed once v1.22.2 is released, scroll down for details...
---
Since upgrading one of my Macs to Ventura 13.0, my folder will no longer sync (getting stuck on a piece of undocumented metadata called `com.apple.provenance`

I have tried removing the xattr with `sudo xattr -d com.apple.provenance /path/to/file` but that isn't working either.

Google has nothing about this really... anyone else running into this? Using syncthing-macos 1.22.0-1

_see [related post on ST forum](https://forum.syncthing.net/t/com-apple-provenance/19262)_

**Comment by xor-gate** [comment] 2022-11-05 21:27
Thanks for the report, I have old hardware which doesn't run Ventura. So I need to figure out a way to reproduce this or dig up some documentation. I think it is some sort of extra security mechanism (again). Probably I need some help from other people with this unfortunately.

**Comment by luckman212** [comment] 2022-11-05 21:52
Thanks, I've just posted a question over on [AskDifferent][1] as well.

[1]: https://apple.stackexchange.com/questions/450118/what-is-the-com-apple-provenance-xattr-extended-attribute-and-how-can-i-dele

**Comment by xor-gate** [comment] 2022-11-06 04:33
Hi @calmh I moved it to the https://github.com/syncthing/syncthing project as it is a Syncthing (macOS build) issue and not part of the syncthing-macos application bundle. Thanks!

**Comment by xor-gate** [comment] 2022-11-06 04:36
Moved because it is not an `syncthing-macos` application bundle problem. But the Syncthing daemon itself with trying to sync xattrs between two devices with macOS Ventura 13.0 and macOS < 13.0. See also the [forum](https://forum.syncthing.net/t/com-apple-provenance/19262).

**Comment by calmh** [comment] 2022-11-06 09:21
As noted on the forum, this can be disabled by configuration, unfortunately only by hand editing the config at the moment:

```
<folder id="..." ...>
  <xattrFilter>
    ...
    <entry match="com.apple.provenance" permit="false"/>
    <entry match="*" permit="true"/>
  </xattrFilter>
</folder>
```

We might want to look into some sort of default black list per operating system perhaps, in the future.

**Comment by xor-gate** [comment] 2022-11-06 09:49
I need to document [the note on manual file editing](https://forum.syncthing.net/t/com-apple-provenance/19262/8) in the FAQ so I transfered the issue back to syncthing-macos.

> As noted on the forum, this can be disabled by configuration, unfortunately only by hand editing > the config at the moment:
> 
> ```
> <folder id="..." ...>
>  <xattrFilter>
>    ...
>  <entry match="com.apple.provenance" permit="false"/>
>  <entry match="*" permit="true"/>
>  </xattrFilter>
> </folder>
> ```
> 
> We might want to look into some sort of default black list per operating system perhaps, in the > future.

See also
https://github.com/syncthing/syncthing-macos/issues/185#issuecomment-1304748701

I leave this open until I have documented this in the README.md

Thanks @luckman212 for reporting

**Comment by xor-gate** [comment] 2022-11-06 18:30
The README.md has been updated with appropiate information. Manual editing is the only way for now. See commit https://github.com/syncthing/syncthing-macos/commit/7fa1d1a0daa234638f0a3241f833da76677c8231

**Comment by luckman212** [comment] 2022-11-08 15:21
Adding a note here, regarding somewhat-related bug [#8657](https://github.com/syncthing/syncthing/issues/8657) (since it relates to syncing xattrs)

**Comment by xor-gate** [comment] 2022-11-08 16:38
Note from @luckman212 (here https://github.com/syncthing/syncthing-macos/issues/154#issuecomment-1307221618) copied over here for convience:

Just adding this note here related to debugging going on over at https://forum.syncthing.net/t/com-apple-provenance/19262/17

For anyone who wants to increase the logfile size using the macOS bundle, you can use:
```shell
# sets logfile size to 50MB, and keep the last 5 during logrotate 
defaults write com.github.xor-gate.syncthing-macosx Arguments '--log-max-size=52428800 --log-max-old-files=5'
```
And when you're done debugging, use this to revert things back to default:
```shell
defaults delete com.github.xor-gate.syncthing-macosx Arguments
```
I believe you need to fully quit the Syncthing app after each of these changes (not just stop/start the service) for it to take effect.

Thanks @luckman212 !

**Comment by xor-gate** [comment] 2022-11-08 16:49
Commenting on your findings:

> I believe you need to fully quit the Syncthing app after each of these changes (not just stop/start the service) for it to take effect.

Yes the `Arguments` are loaded only on startup. Not when changed.

**Comment by luckman212** [comment] 2022-11-09 13:57
@xor-gate [v1.22.2-rc.1][1] was pushed that aims to fix this, among other things. Is it possible for me to compile my own bundle to test? I have Xcode 14.1 but I don't have a Developer account so I can only sign locally.

[1]: https://github.com/syncthing/syncthing/releases/tag/v1.22.2-rc.1

**Comment by luckman212** [comment] 2022-11-10 18:34
@xor-gate Answered my own question... and I'm happy to report that this pre-release build has fixed the original issue for me. :rocket: So hopefully once the upstream release drops we can all benefit.

For anyone else who's curious: here are the steps I figured out in order to build a pre-release. It was confusing at first because the default repo branch is `develop` which is very far out of date from the latest release. I had to clone the 1.22.1-1 branch and build from that in order to get it to work (a full clone and separate `git checkout` would probably work fine too).

### Steps

1. Clone the repo & some prereqs
```shell
git clone --depth 1 --branch v1.22.1-1 https://github.com/syncthing/syncthing-macos
cd syncthing-macos
git submodule update --init
```
2. Change version strings
```shell
vi syncthing/Scripts/syncthing-resource.sh
```
- update `SYNCTHING_VERSION` (removing the `v`):
```
SYNCTHING_VERSION="1.22.2-rc.1"
```
- update `CFBundleShortVersionString` in **Info.plist**:
```shell
vi syncthing/Info.plist
```
3. find & export your developer account / codesigning identity:
```shell
security find-identity -v -p codesigning
export SYNCTHING_APP_CODE_SIGN_IDENTITY="Apple Development: you@domain (XXXXXXXXXX)"
```
4. build
```shell
make release
```
5. look in syncthing-macos/Build/Products/Release/ for your newly minted **Syncthing.app**

<img src=https://user-images.githubusercontent.com/1992842/201177223-136d32c7-ff1e-4642-a5eb-2fff5d3fdf3e.png width=252>

**Comment by xor-gate** [comment] 2022-11-10 20:22
`syncthing-macos` only ships releases no `-rc`s. The `README.md` includes some build and release management instructions. I will include this build instructions into the readme when I have some spare time. Thanks for reporting the issue is resolved.

**Comment by luckman212** [comment] 2022-11-10 22:10
Not fully out of the woods yet on this one... https://github.com/syncthing/syncthing/issues/8667

**Comment by luckman212** [comment] 2022-11-11 13:04
Compiled a build this morning based on [v1.22.2-rc.2][1] and this is now 100% fixed for me 👍 

[1]: https://github.com/syncthing/syncthing/releases/tag/v1.22.2-rc.2

**Comment by xor-gate** [comment] 2022-11-11 18:12
Good, we need to wait for the v1.22.2 release window on 6 dec. Then we can close this ticket. Thanks for your effort!

**Comment by luckman212** [comment] 2022-11-22 22:02
Still looking good, on [1.22.2-rc.3][1] now and all is working well.

[1]: https://github.com/syncthing/syncthing/releases/tag/v1.22.2-rc.3

**Comment by xor-gate** [comment] 2022-12-09 22:07
Syncthing macOS is now shipping with release v1.22.2 (see commit https://github.com/syncthing/syncthing-macos/commit/bf62e121108d188e68d346ceb92c150630b0808b). Only the [auto-updater is broken for some unknown reason](https://forum.syncthing.net/t/syncthing-for-macos/2745/58), you can wait or [download the signed/secure DMG](https://github.com/syncthing/syncthing-macos/releases/tag/v1.22.2-1).

**Closed as completed by xor-gate** 2022-12-09 22:07 UTC
Labels: bug
