### ISSUE TITLE
Autoupdate don't work - Downgrade from 145201 to 100001 not allowed

### ISSUE THREAD

**Issue by expiredemulsion** [xor-gate/syncthing-macosx#90] opened 2019-01-13 15:38 UTC
Upgrading from 0.14.52.1 only to get a notice that I’m not allowed to downgrade to 100001.
Seems the version control check gets confused by the leading 0.

Syncthing.app 0.14.52-1
macOS 10.14.2 (18C54)
![0 14-to-1 0](https://user-images.githubusercontent.com/2619582/51087283-a7695a00-1751-11e9-807e-6e50302bca9f.png)

**Comment by martijndeb** [comment] 2019-01-13 20:12
Ah, I came here because I have this as well. Manually downloading the dmg and overwriting syncthing.app works.

**Comment by xor-gate** [comment] 2019-01-13 20:34
Oops I screwed up and the version integer string missed an extra zero. Hopefully it works now. @calmh  could you deploy the fixed appcast generator?

**Comment by calmh** [comment] 2019-01-14 07:24
I can, but the previous one should have been sufficient. Without your latest change, `145201 -> 10000001`, with your latest change `100000001`... It was already two digits longer, now it's three digits longer.

**Comment by xor-gate** [comment] 2019-01-16 09:09
Oops sorry guys I was not very precise with this, I will revert the generator and upload release v1.0.0-2:

```
1000002 (10 00 00 2) -> tag v1.0.0-2
100001  (10 00 01)   -> tag v1.0.0-1
145401  (14 54 01)   -> tag v0.14.54-1
```

-_-"

**Comment by xor-gate** [comment] 2019-01-16 09:58
The updater has been tested by myself and works again. @expiredemulsion could you verify and close the issue? Thanks!

**Comment by calmh** [comment] 2019-01-16 10:09
So just that we're on the same page, the current code is

```
... "%03d%02d%02d%02d", rSegments[0] * 10, rSegments[1], rSegments[2], distVersion
```

which for 1.0.0-2 will yield

`010 00 00 02` (spaces for clarity)

which is a different number of zeroes both in the middle and in the front, compared to what you commented above :)

It's also a lesser number of zeroes than what's currently out there, which will make it a downgrade again, so I don't t think you can do this revert?
 
```
$ curl -s https://upgrades.syncthing.net/syncthing-macos/appcast.xml | grep sparkle:version
      <enclosure sparkle:shortVersionString="v1.0.0-2" sparkle:version="100000002" type="application/octet-stream" url="https://github.com/syncthing/syncthing-macos/releases/download/v1.0.0-2/Syncthing-1.0.0-2.dmg"></enclosure>
```

I would suggest the following:

```
"%d%03d%03d%02d", rSegments[0], rSegments[1], rSegments[2], distVersion
```

That'll yield `1 000 000 02` (same as current) for 1.0.0-2 and increment cleanly from there with lots of space for minor/patch versions.

**Comment by xor-gate** [comment] 2019-01-16 11:41
I agree, next release I will use the suggested `"%d%03d%03d%02d", rSegments[0], rSegments[1], rSegments[2], distVersion` scheme.

**Comment by xor-gate** [comment] 2019-01-16 11:44
@calmh please leave the appcast generator as-is in the production environment for the time until the next wrapper release so people installations can keep up with the latest before we probably break it again.

**Comment by core-code** [comment] 2019-01-16 17:50
the latest release claims to be outdated, see screenshot, however when updating it it will just claim to be outdated again:

<img width="732" alt="screenshot 2019-01-16 at 18 47 12" src="https://user-images.githubusercontent.com/1261954/51268085-7726f300-19bf-11e9-9089-e095c4025d22.png">


the appcast here:
https://upgrades.syncthing.net/syncthing-macos/appcast.xml

contains two zeroes too many, it should read
sparkle:version="1000002"
and not
sparkle:version="100000002"

**Comment by xor-gate** [comment] 2019-01-16 18:09
Hopefully the last try will fix it for real, i have patched the v1.0.0-2 tag with the latest suggestions from calmh. The problem is both versions (appcast and Info.plist) need to be in sync.

**Comment by expiredemulsion** [comment] 2019-01-16 18:20
I'm on 1.0.0-1 and it tells me to "upgrade" to 0.14.52
![1 0 0-1](https://user-images.githubusercontent.com/2619582/51269805-b2c3bc00-19c3-11e9-93fb-3dca5850ff9d.png)

**Comment by xor-gate** [comment] 2019-01-16 18:22
@expiredemulsion could you try to load again -> trayicon -> about -> check for updates? Mine was locally also on 1.0.0-1 and upgraded fine. I did revoke the appcast 1.0.0-2 which made things even worse.

<img width="623" alt="screenshot 2019-01-16 at 19 23 40" src="https://user-images.githubusercontent.com/1050166/51270049-45645b00-19c4-11e9-8d62-47a63a985b07.png">

**Comment by expiredemulsion** [comment] 2019-01-16 18:25
@xor-gate 
Thanks! Now I have the same upgrade notice as you do!

**Comment by core-code** [comment] 2019-01-16 18:28
confirmed fixed

**Comment by xor-gate** [comment] 2019-01-16 18:33
![](https://media.giphy.com/media/c6DIpCp1922KQ/giphy.gif)

I almost jumped out of the window with this zero madness. Thanks all for the notices!

**Comment by calmh** [comment] 2019-01-16 19:24
Auto update logic is one of those things one needs to be very careful when changing. As we've learned, painfully, several times. ;)

**Comment by xor-gate** [comment] 2019-01-20 08:59
Next time I will think 3 times, discus with other people, implement and check 3 times again 🙈

**Closed as completed by xor-gate** 2019-01-20 08:59 UTC
Labels: bug, frozen-due-to-age
