### ISSUE TITLE
Two instances of syncthing in Activity monitor

### ISSUE THREAD

**Issue by enaloha** [xor-gate/syncthing-macosx#39] opened 2017-08-14 02:58 UTC
After updating tp the latest version, I see two syncthing processes. The previous version showed only one executable running. Haven't noticed any problems with that, but thought I should mention.

![image](https://user-images.githubusercontent.com/13284542/29256744-647d5562-8048-11e7-9ddc-3326a814fac1.png)

**Comment by xor-gate** [comment] 2017-08-14 05:41
I can verify this also on my system. They are sub processes of each other so no double syncthing instances are running (multithreaded application). See my activity log screenshot below with detailed process info.

<img width="532" alt="screen shot 2017-08-14 at 07 40 06" src="https://user-images.githubusercontent.com/1050166/29259575-dc25169c-80c3-11e7-8cf9-2044d754a64e.png">

**Comment by enaloha** [comment] 2017-08-19 17:30
I have observed this issue and I think it might be a bug (or at least a problem). I don't think this has anything to do with multi-threading. These are clearly two processes with individual PIDs (if each app would open a PID for each thread it would be crazy. Anyway, the problem is that whenever Syncthing hangs and I need to terminate via the "Quit Syncthing" menu item, Syncthing will hang because it cannot shut down both PIDs (only one is closed).

**Comment by xor-gate** [comment] 2017-08-19 20:33
Yes syncthing-macosx bundle starts syncthing daemon as its child process and are two separated processes. It weird you have to kill syncthing, I have not had any problem with it as long as I'm using my own syncthing-macosx. But you are right it should be "easier to kill". A simple solution  doesn't come to my mind yet.

**Comment by virusman** [comment] 2017-08-19 20:43
Yeah, I see the same thing: syncthing forks a new process upon launch. I think this is by design. I launched syncthing from command line, and it also spawned two processes.
@enaloha Threads and processes are different things, both can be used for different reasons; and forking new processes is definitely common practice for daemons.

**Comment by xor-gate** [comment] 2017-08-19 20:45
This is the nature of golang applications, it always spawns minimal two processes. The runtime automatically scales over multiple threads.

**Comment by xor-gate** [comment] 2017-09-12 09:00
To protect against two running syncthing-macosx syncthing daemons we could store a pidfile and try to kill it before starting a new instance. But this needs some work.

**Comment by xor-gate** [comment] 2018-06-04 16:03
I'm closing this, as I think it as I have investigated earlier. Its just a sub-process of syncthing. It would also be nice to control the actual start/stop/restart of the subprocess (See https://github.com/xor-gate/syncthing-macosx/issues/48).

**Closed by xor-gate** 2018-06-04 16:03 UTC
Labels: invalid
