### ISSUE TITLE
FATAL: Database Schema: Syncthing v1.4.0 required

### ISSUE THREAD

**Issue by zeronymous** [xor-gate/syncthing-macosx#113] opened 2020-04-26 23:56 UTC
after running syncthing-macos v1.0.0-2, the toolbar menu shows syncthing repeatedly attempting to start, failing and retrying.  GUI is unavailable in the browser.  

Starting via command line shows the following error: 
FATAL: Database Schema: Syncthing v1.4.0 required

this occurs even after uninstalling and installing again.  

System: OSX 10.15.4 Catalina

**Comment by imsodin** [comment] 2020-04-27 06:46
I guess the problem is that the installer comes with an old version and uses auto-upgrades. so you had a newer version previously which changed your db. now the old version fails to upgrade (which is also fixed in a new version).

solution: on cmd run syncthing -upgrade

**Comment by xor-gate** [comment] 2020-04-29 18:11
I tried to create a new release but we have some issues with it #111

**Comment by xor-gate** [comment] 2020-06-03 16:49
Latest v1.6.1 release fixes it, please test.

**Closed as completed by xor-gate** 2020-06-03 16:49 UTC
Labels: frozen-due-to-age

**Comment by xor-gate** [comment] 2020-06-03 16:50
When it doesn't work you should perform the following steps:
- Stop syncthing
- Open Terminal.app
- Execute `rm -Rf ~/Library/Application\ Support/Syncthing-macOS`
- Start syncthing
