### ISSUE TITLE
Suggestion: confusing client and server communication compare to Dropbox

### ISSUE THREAD

**Issue by dipenpatel235** [xor-gate/syncthing-macosx#33] opened 2017-08-02 09:05 UTC
Hello..
i am using this Syncthing for Mac and Windows.
but it is some confusing to user friendly compare to dropbox.
we have faced below isssue.
 - after set default folder not able to change that folder location.
 - not given Default Storage location like "/Syncthin" or "C:/Syncthing"
 - On Every New Folder Share get request on client to add allow folder.
 -For Mac required to copy paste Secrate key

**Comment by xor-gate** [comment] 2017-08-02 09:08
The first two items I cannot help with. The copy-pasting of the API key is already an issue (autoconfigure without user intervention). Closing this as this is a duplicate of #31.

**Closed by xor-gate** 2017-08-02 09:08 UTC

**Comment by jibinkumar** [comment] 2017-08-03 05:53
Thanks for fixing #31 I will have a look sometime today. What Dipen suggested sounds interesting. If Syncthing could have a default location, or may be if setting up 'Folder location' is a single step, it would look more organized. Just like Google Drive and Dropbox, where user can choose a default location and all files remains in that parent folder.
